"""laws catalog

Revision ID: 5fa216d0d09f
Revises: b8b045705028
Create Date: 2026-08-26 00:20:53.210971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa216d0d09f'
down_revision: Union[str, Sequence[str], None] = 'b8b045705028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laws',
    sa.Column('law_id', sa.String(length=64), nullable=False),
    sa.Column('law_name', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('issuer', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('law_id')
    )
    op.create_index(op.f('ix_laws_category'), 'laws', ['category'], unique=False)
    op.create_index(op.f('ix_laws_created_at'), 'laws', ['created_at'], unique=False)
    op.create_index(op.f('ix_laws_doc_type'), 'laws', ['doc_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laws_doc_type'), table_name='laws')
    op.drop_index(op.f('ix_laws_created_at'), table_name='laws')
    op.drop_index(op.f('ix_laws_category'), table_name='laws')
    op.drop_table('laws')
    # ### end Alembic commands ###
