"""baseline schema

Tạo toàn bộ bảng nghiệp vụ, bảng corpus ``legal_knowledge_records`` và hạ tầng
full-text search tiếng Việt (bỏ dấu + trigram).

Revision ID: b8b045705028
Revises:
Create Date: 2026-08-25 23:58:26.450791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import src.models.mixins


# revision identifiers, used by Alembic.
revision: str = 'b8b045705028'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Extension và hàm unaccent IMMUTABLE thường đã có sẵn qua
# docker/postgres/init.sql. Lặp lại ở đây để migration chạy được trên
# PostgreSQL dựng bằng cách khác (managed service, CI...).
#
# Tách thành từng câu lệnh riêng: asyncpg dùng prepared statement nên không nhận
# nhiều lệnh trong một lần execute.
FTS_PREREQUISITES = (
    "CREATE EXTENSION IF NOT EXISTS unaccent",
    "CREATE EXTENSION IF NOT EXISTS pg_trgm",
    # unaccent() mặc định STABLE nên không dùng được trong generated column.
    "CREATE OR REPLACE FUNCTION immutable_unaccent(text) "
    "RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT "
    "AS $$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $$",
)

def upgrade() -> None:
    """Upgrade schema."""
    for statement in FTS_PREREQUISITES:
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('due_month_offset', sa.Integer(), nullable=False),
    sa.Column('due_fixed_month', sa.Integer(), nullable=True),
    sa.Column('legal_refs', src.models.mixins.JSONBType(), nullable=False),
    sa.Column('applies_to', src.models.mixins.JSONBType(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_compliance_rules_created_at'), 'compliance_rules', ['created_at'], unique=False)
    op.create_table('legal_knowledge_records',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('law_id', sa.Text(), nullable=False),
    sa.Column('law_name', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('chapter', sa.Text(), nullable=True),
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('article_title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('extra', src.models.mixins.JSONBType(), nullable=False),
    # Generated column: PostgreSQL tự tính nên không thể lệch với dữ liệu gốc.
    sa.Column(
        'article_number',
        sa.BigInteger(),
        sa.Computed("NULLIF(substring(article from '[0-9]+'), '')::bigint", persisted=True),
        nullable=True,
    ),
    sa.Column(
        'doc_ref',
        sa.String(length=512),
        sa.Computed("law_id || '|' || law_name", persisted=True),
        nullable=True,
    ),
    # PostgreSQL không có từ điển tiếng Việt: dùng cấu hình 'simple' trên text
    # đã bỏ dấu. Trọng số A/B/C để tiêu đề Điều xếp trên nội dung khi cùng khớp.
    sa.Column(
        'search_vector',
        postgresql.TSVECTOR(),
        sa.Computed(
            "setweight(to_tsvector('simple', immutable_unaccent(coalesce(article_title, ''))), 'A') || "
            "setweight(to_tsvector('simple', immutable_unaccent(coalesce(law_name, ''))), 'B') || "
            "setweight(to_tsvector('simple', immutable_unaccent(coalesce(article, ''))), 'B') || "
            "setweight(to_tsvector('simple', immutable_unaccent(coalesce(content, ''))), 'C')",
            persisted=True,
        ),
        nullable=True,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_legal_knowledge_law_order', 'legal_knowledge_records', ['law_id', 'article_number'], unique=False)
    op.create_index('idx_legal_knowledge_reference', 'legal_knowledge_records', ['law_id', 'article'], unique=False)
    op.create_index(
        'idx_legal_search_vector',
        'legal_knowledge_records',
        ['search_vector'],
        postgresql_using='gin',
    )
    # Trigram để cứu truy vấn gõ sai/thiếu dấu mà full-text không khớp token nào.
    op.execute(
        "CREATE INDEX idx_legal_title_trgm ON legal_knowledge_records "
        "USING gin (immutable_unaccent(article_title) gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX idx_legal_law_name_trgm ON legal_knowledge_records "
        "USING gin (immutable_unaccent(law_name) gin_trgm_ops)"
    )
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=32), nullable=True),
    sa.Column('business_type', sa.String(length=64), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('annual_revenue_bn', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('vat_period', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_code')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_table('compliance_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'rule_id', 'period_label', name='uq_compliance_task_period')
    )
    op.create_index(op.f('ix_compliance_tasks_created_at'), 'compliance_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_due_date'), 'compliance_tasks', ['due_date'], unique=False)
    op.create_index('ix_compliance_tasks_org_due', 'compliance_tasks', ['organization_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_organization_id'), 'compliance_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_rule_id'), 'compliance_tasks', ['rule_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('detail', src.models.mixins.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_table('contract_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('clause_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_reviews_created_at'), 'contract_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_contract_reviews_document_id'), 'contract_reviews', ['document_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', src.models.mixins.JSONBType(), nullable=False),
    sa.Column('relevant_docs', src.models.mixins.JSONBType(), nullable=False),
    sa.Column('trace', src.models.mixins.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('contract_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('clause_title', sa.String(length=255), nullable=True),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('legal_refs', src.models.mixins.JSONBType(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_findings_review_id'), 'contract_findings', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_findings_review_id'), table_name='contract_findings')
    op.drop_table('contract_findings')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_contract_reviews_document_id'), table_name='contract_reviews')
    op.drop_index(op.f('ix_contract_reviews_created_at'), table_name='contract_reviews')
    op.drop_table('contract_reviews')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_conversations_user_updated', table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_compliance_tasks_rule_id'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_organization_id'), table_name='compliance_tasks')
    op.drop_index('ix_compliance_tasks_org_due', table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_due_date'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_created_at'), table_name='compliance_tasks')
    op.drop_table('compliance_tasks')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.execute("DROP INDEX IF EXISTS idx_legal_law_name_trgm")
    op.execute("DROP INDEX IF EXISTS idx_legal_title_trgm")
    op.drop_index('idx_legal_search_vector', table_name='legal_knowledge_records')
    op.drop_index('idx_legal_knowledge_reference', table_name='legal_knowledge_records')
    op.drop_index('idx_legal_knowledge_law_order', table_name='legal_knowledge_records')
    op.drop_table('legal_knowledge_records')
    op.drop_index(op.f('ix_compliance_rules_created_at'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
